erDiagram
    COLECAO ||--o{ ESTAMPA : contem
    COLECAO ||--o{ CHAVEIRO : contem

    COLECAO {
        int colecao_id PK
        string nome
        date data_inicio
        date data_fim
    }

    ESTAMPA {
        int estampa_id PK
        string nome
        int quantidade
        int colecao_id FK
    }

    PECA {
        int peca_id PK
        string tipo
        string tamanho
        string cor
        int quantidade
    }


    ADESIVO{
        int adesivo_id PK
        string adesivo_modelo
        boolean cromatico
    }

    CHAVEIRO{
        int chaveiro_id PK
        string chaveiro_modelo
        int colecao_id FK
    }
