erDiagram
    COLECAO ||--o{ ESTAMPA : contem
    COLECAO ||--o{ CHAVEIRO : contem
    USUARIO ||--o{ HISTORICO_ALTERACAO : registra

    USUARIO {
        int usuarioId PK
        string nome
        string senha
        string tipo  "ADMINISTRADOR|FUNCIONARIO"
    }

    COLECAO {
        int colecaoId PK
        string nome
        date dataInicio
        date dataFim
    }

    ESTAMPA {
        int estampaId PK
        string nome
        int quantidade
        int colecaoId FK
    }

    PECA {
        int pecaId PK
        string tipo
        string tamanho
        string cor
        int quantidade
    }

    ADESIVO {
        int adesivoId PK
        string adesivo_modelo
        boolean cromatico
    }

    CHAVEIRO {
        int chaveiroId PK
        string chaveiroModelo
        int colecaoId FK
    }

    HISTORICO_ALTERACAO {
        int id PK
        string entidade         "Nome da entidade alterada (ex: 'Peca')"
        int entidadeId         "ID da entidade alterada"
        string campoAlterado   "Campo alterado (ex: 'quantidade')"
        string valorAntigo
        string valorNovo
        datetime dataHora
        int usuarioId FK
    }
