erDiagram
    COLECAO ||--o{ ESTAMPA : contem
    COLECAO ||--o{ CHAVEIRO : contem
    USUARIO ||--o{ HISTORICO_ALTERACAO : registra

    USUARIO {
        int usuario_id PK
        string nome
        string senha
        string tipo  "ADMINISTRADOR|FUNCIONARIO"
    }

    COLECAO {
        int colecao_id PK
        string nome
        date data_inicio
        date data_fim
    }

    ESTAMPA {
        int estampa_id PK
        string nome
        int quantidade
        int colecao_id FK
    }

    PECA {
        int peca_id PK
        string tipo
        string tamanho
        string cor
        int quantidade
    }

    ADESIVO {
        int adesivo_id PK
        string adesivo_modelo
        boolean cromatico
    }

    CHAVEIRO {
        int chaveiro_id PK
        string chaveiro_modelo
        int colecao_id FK
    }

    HISTORICO_ALTERACAO {
        int id PK
        string entidade         "Nome da entidade alterada (ex: 'Peca')"
        int entidade_id         "ID da entidade alterada"
        string campo_alterado   "Campo alterado (ex: 'quantidade')"
        string valor_antigo
        string valor_novo
        datetime data_hora
        int usuario_id FK
    }
